#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLGaRa")]
	public partial class QLGaraDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNGUOIDUNG(NGUOIDUNG instance);
    partial void UpdateNGUOIDUNG(NGUOIDUNG instance);
    partial void DeleteNGUOIDUNG(NGUOIDUNG instance);
    partial void InsertTHO(THO instance);
    partial void UpdateTHO(THO instance);
    partial void DeleteTHO(THO instance);
    partial void InsertCHITIET_HD(CHITIET_HD instance);
    partial void UpdateCHITIET_HD(CHITIET_HD instance);
    partial void DeleteCHITIET_HD(CHITIET_HD instance);
    partial void InsertCONGVIEC(CONGVIEC instance);
    partial void UpdateCONGVIEC(CONGVIEC instance);
    partial void DeleteCONGVIEC(CONGVIEC instance);
    partial void InsertHOPDONG(HOPDONG instance);
    partial void UpdateHOPDONG(HOPDONG instance);
    partial void DeleteHOPDONG(HOPDONG instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertNGUOIDUNG1(NGUOIDUNG1 instance);
    partial void UpdateNGUOIDUNG1(NGUOIDUNG1 instance);
    partial void DeleteNGUOIDUNG1(NGUOIDUNG1 instance);
    partial void InsertPHIEUTHU(PHIEUTHU instance);
    partial void UpdatePHIEUTHU(PHIEUTHU instance);
    partial void DeletePHIEUTHU(PHIEUTHU instance);
    partial void InsertTHO1(THO1 instance);
    partial void UpdateTHO1(THO1 instance);
    partial void DeleteTHO1(THO1 instance);
    #endregion
		
		public QLGaraDataContext() : 
				base(global::LINQ.Properties.Settings.Default.QLGaRaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLGaraDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLGaraDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLGaraDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLGaraDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this.GetTable<NGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<THO> THOs
		{
			get
			{
				return this.GetTable<THO>();
			}
		}
		
		public System.Data.Linq.Table<ADMIN1> ADMIN1s
		{
			get
			{
				return this.GetTable<ADMIN1>();
			}
		}
		
		public System.Data.Linq.Table<CHITIET_HD> CHITIET_HDs
		{
			get
			{
				return this.GetTable<CHITIET_HD>();
			}
		}
		
		public System.Data.Linq.Table<CONGVIEC> CONGVIECs
		{
			get
			{
				return this.GetTable<CONGVIEC>();
			}
		}
		
		public System.Data.Linq.Table<HOPDONG> HOPDONGs
		{
			get
			{
				return this.GetTable<HOPDONG>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG1> NGUOIDUNG1s
		{
			get
			{
				return this.GetTable<NGUOIDUNG1>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTHU> PHIEUTHUs
		{
			get
			{
				return this.GetTable<PHIEUTHU>();
			}
		}
		
		public System.Data.Linq.Table<THO1> THO1s
		{
			get
			{
				return this.GetTable<THO1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN
	{
		
		private string _TenAdmin;
		
		private string _MatKhau;
		
		public ADMIN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenAdmin", DbType="NVarChar(50)")]
		public string TenAdmin
		{
			get
			{
				return this._TenAdmin;
			}
			set
			{
				if ((this._TenAdmin != value))
				{
					this._TenAdmin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this._MatKhau = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG")]
	public partial class NGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenNguoiDung;
		
		private string _MatKhau;
		
		private System.Nullable<int> _MaKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenNguoiDungChanging(string value);
    partial void OnTenNguoiDungChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    #endregion
		
		public NGUOIDUNG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiDung", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenNguoiDung
		{
			get
			{
				return this._TenNguoiDung;
			}
			set
			{
				if ((this._TenNguoiDung != value))
				{
					this.OnTenNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiDung = value;
					this.SendPropertyChanged("TenNguoiDung");
					this.OnTenNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(20)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THO")]
	public partial class THO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTho;
		
		private string _TenTho;
		
		private System.Nullable<int> _Nhom;
		
		private System.Nullable<int> _NhomTruong;
		
		private EntitySet<THO> _THOs;
		
		private EntityRef<THO> _THO1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThoChanging(int value);
    partial void OnMaThoChanged();
    partial void OnTenThoChanging(string value);
    partial void OnTenThoChanged();
    partial void OnNhomChanging(System.Nullable<int> value);
    partial void OnNhomChanged();
    partial void OnNhomTruongChanging(System.Nullable<int> value);
    partial void OnNhomTruongChanged();
    #endregion
		
		public THO()
		{
			this._THOs = new EntitySet<THO>(new Action<THO>(this.attach_THOs), new Action<THO>(this.detach_THOs));
			this._THO1 = default(EntityRef<THO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTho", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTho
		{
			get
			{
				return this._MaTho;
			}
			set
			{
				if ((this._MaTho != value))
				{
					this.OnMaThoChanging(value);
					this.SendPropertyChanging();
					this._MaTho = value;
					this.SendPropertyChanged("MaTho");
					this.OnMaThoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTho", DbType="NVarChar(50)")]
		public string TenTho
		{
			get
			{
				return this._TenTho;
			}
			set
			{
				if ((this._TenTho != value))
				{
					this.OnTenThoChanging(value);
					this.SendPropertyChanging();
					this._TenTho = value;
					this.SendPropertyChanged("TenTho");
					this.OnTenThoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhom", DbType="Int")]
		public System.Nullable<int> Nhom
		{
			get
			{
				return this._Nhom;
			}
			set
			{
				if ((this._Nhom != value))
				{
					this.OnNhomChanging(value);
					this.SendPropertyChanging();
					this._Nhom = value;
					this.SendPropertyChanged("Nhom");
					this.OnNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomTruong", DbType="Int")]
		public System.Nullable<int> NhomTruong
		{
			get
			{
				return this._NhomTruong;
			}
			set
			{
				if ((this._NhomTruong != value))
				{
					if (this._THO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNhomTruongChanging(value);
					this.SendPropertyChanging();
					this._NhomTruong = value;
					this.SendPropertyChanged("NhomTruong");
					this.OnNhomTruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THO_THO", Storage="_THOs", ThisKey="MaTho", OtherKey="NhomTruong")]
		public EntitySet<THO> THOs
		{
			get
			{
				return this._THOs;
			}
			set
			{
				this._THOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THO_THO", Storage="_THO1", ThisKey="NhomTruong", OtherKey="MaTho", IsForeignKey=true)]
		public THO THO1
		{
			get
			{
				return this._THO1.Entity;
			}
			set
			{
				THO previousValue = this._THO1.Entity;
				if (((previousValue != value) 
							|| (this._THO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THO1.Entity = null;
						previousValue.THOs.Remove(this);
					}
					this._THO1.Entity = value;
					if ((value != null))
					{
						value.THOs.Add(this);
						this._NhomTruong = value.MaTho;
					}
					else
					{
						this._NhomTruong = default(Nullable<int>);
					}
					this.SendPropertyChanged("THO1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THOs(THO entity)
		{
			this.SendPropertyChanging();
			entity.THO1 = this;
		}
		
		private void detach_THOs(THO entity)
		{
			this.SendPropertyChanging();
			entity.THO1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN1
	{
		
		private string _TenAdmin;
		
		private string _MatKhau;
		
		public ADMIN1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenAdmin", DbType="NVarChar(50)")]
		public string TenAdmin
		{
			get
			{
				return this._TenAdmin;
			}
			set
			{
				if ((this._TenAdmin != value))
				{
					this._TenAdmin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this._MatKhau = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIET_HD")]
	public partial class CHITIET_HD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SoHD;
		
		private string _MaCV;
		
		private System.Nullable<int> _TriGiaCV;
		
		private System.Nullable<int> _MaTho;
		
		private System.Nullable<int> _KhoanTho;
		
		private EntityRef<CONGVIEC> _CONGVIEC;
		
		private EntityRef<HOPDONG> _HOPDONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoHDChanging(int value);
    partial void OnSoHDChanged();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnTriGiaCVChanging(System.Nullable<int> value);
    partial void OnTriGiaCVChanged();
    partial void OnMaThoChanging(System.Nullable<int> value);
    partial void OnMaThoChanged();
    partial void OnKhoanThoChanging(System.Nullable<int> value);
    partial void OnKhoanThoChanged();
    #endregion
		
		public CHITIET_HD()
		{
			this._CONGVIEC = default(EntityRef<CONGVIEC>);
			this._HOPDONG = default(EntityRef<HOPDONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SoHD
		{
			get
			{
				return this._SoHD;
			}
			set
			{
				if ((this._SoHD != value))
				{
					if (this._HOPDONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoHDChanging(value);
					this.SendPropertyChanging();
					this._SoHD = value;
					this.SendPropertyChanged("SoHD");
					this.OnSoHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					if (this._CONGVIEC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TriGiaCV", DbType="Int")]
		public System.Nullable<int> TriGiaCV
		{
			get
			{
				return this._TriGiaCV;
			}
			set
			{
				if ((this._TriGiaCV != value))
				{
					this.OnTriGiaCVChanging(value);
					this.SendPropertyChanging();
					this._TriGiaCV = value;
					this.SendPropertyChanged("TriGiaCV");
					this.OnTriGiaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTho", DbType="Int")]
		public System.Nullable<int> MaTho
		{
			get
			{
				return this._MaTho;
			}
			set
			{
				if ((this._MaTho != value))
				{
					this.OnMaThoChanging(value);
					this.SendPropertyChanging();
					this._MaTho = value;
					this.SendPropertyChanged("MaTho");
					this.OnMaThoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoanTho", DbType="Int")]
		public System.Nullable<int> KhoanTho
		{
			get
			{
				return this._KhoanTho;
			}
			set
			{
				if ((this._KhoanTho != value))
				{
					this.OnKhoanThoChanging(value);
					this.SendPropertyChanging();
					this._KhoanTho = value;
					this.SendPropertyChanged("KhoanTho");
					this.OnKhoanThoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGVIEC_CHITIET_HD", Storage="_CONGVIEC", ThisKey="MaCV", OtherKey="MaCV", IsForeignKey=true)]
		public CONGVIEC CONGVIEC
		{
			get
			{
				return this._CONGVIEC.Entity;
			}
			set
			{
				CONGVIEC previousValue = this._CONGVIEC.Entity;
				if (((previousValue != value) 
							|| (this._CONGVIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CONGVIEC.Entity = null;
						previousValue.CHITIET_HDs.Remove(this);
					}
					this._CONGVIEC.Entity = value;
					if ((value != null))
					{
						value.CHITIET_HDs.Add(this);
						this._MaCV = value.MaCV;
					}
					else
					{
						this._MaCV = default(string);
					}
					this.SendPropertyChanged("CONGVIEC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_CHITIET_HD", Storage="_HOPDONG", ThisKey="SoHD", OtherKey="SoHD", IsForeignKey=true)]
		public HOPDONG HOPDONG
		{
			get
			{
				return this._HOPDONG.Entity;
			}
			set
			{
				HOPDONG previousValue = this._HOPDONG.Entity;
				if (((previousValue != value) 
							|| (this._HOPDONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOPDONG.Entity = null;
						previousValue.CHITIET_HDs.Remove(this);
					}
					this._HOPDONG.Entity = value;
					if ((value != null))
					{
						value.CHITIET_HDs.Add(this);
						this._SoHD = value.SoHD;
					}
					else
					{
						this._SoHD = default(int);
					}
					this.SendPropertyChanged("HOPDONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONGVIEC")]
	public partial class CONGVIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCV;
		
		private string _NoiDungVC;
		
		private System.Nullable<int> _TriGiaCV;
		
		private System.Nullable<int> _KhoanTho;
		
		private EntitySet<CHITIET_HD> _CHITIET_HDs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnNoiDungVCChanging(string value);
    partial void OnNoiDungVCChanged();
    partial void OnTriGiaCVChanging(System.Nullable<int> value);
    partial void OnTriGiaCVChanged();
    partial void OnKhoanThoChanging(System.Nullable<int> value);
    partial void OnKhoanThoChanged();
    #endregion
		
		public CONGVIEC()
		{
			this._CHITIET_HDs = new EntitySet<CHITIET_HD>(new Action<CHITIET_HD>(this.attach_CHITIET_HDs), new Action<CHITIET_HD>(this.detach_CHITIET_HDs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungVC", DbType="VarChar(50)")]
		public string NoiDungVC
		{
			get
			{
				return this._NoiDungVC;
			}
			set
			{
				if ((this._NoiDungVC != value))
				{
					this.OnNoiDungVCChanging(value);
					this.SendPropertyChanging();
					this._NoiDungVC = value;
					this.SendPropertyChanged("NoiDungVC");
					this.OnNoiDungVCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TriGiaCV", DbType="Int")]
		public System.Nullable<int> TriGiaCV
		{
			get
			{
				return this._TriGiaCV;
			}
			set
			{
				if ((this._TriGiaCV != value))
				{
					this.OnTriGiaCVChanging(value);
					this.SendPropertyChanging();
					this._TriGiaCV = value;
					this.SendPropertyChanged("TriGiaCV");
					this.OnTriGiaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoanTho", DbType="Int")]
		public System.Nullable<int> KhoanTho
		{
			get
			{
				return this._KhoanTho;
			}
			set
			{
				if ((this._KhoanTho != value))
				{
					this.OnKhoanThoChanging(value);
					this.SendPropertyChanging();
					this._KhoanTho = value;
					this.SendPropertyChanged("KhoanTho");
					this.OnKhoanThoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGVIEC_CHITIET_HD", Storage="_CHITIET_HDs", ThisKey="MaCV", OtherKey="MaCV")]
		public EntitySet<CHITIET_HD> CHITIET_HDs
		{
			get
			{
				return this._CHITIET_HDs;
			}
			set
			{
				this._CHITIET_HDs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIET_HDs(CHITIET_HD entity)
		{
			this.SendPropertyChanging();
			entity.CONGVIEC = this;
		}
		
		private void detach_CHITIET_HDs(CHITIET_HD entity)
		{
			this.SendPropertyChanging();
			entity.CONGVIEC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOPDONG")]
	public partial class HOPDONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SoHD;
		
		private System.Nullable<System.DateTime> _NgayHD;
		
		private System.Nullable<int> _MaKH;
		
		private string _SoXe;
		
		private System.Nullable<int> _TriGiaHD;
		
		private System.Nullable<System.DateTime> _NgayGiaoDK;
		
		private System.Nullable<System.DateTime> _NgayNgThu;
		
		private EntitySet<CHITIET_HD> _CHITIET_HDs;
		
		private EntitySet<PHIEUTHU> _PHIEUTHUs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoHDChanging(int value);
    partial void OnSoHDChanged();
    partial void OnNgayHDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHDChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnSoXeChanging(string value);
    partial void OnSoXeChanged();
    partial void OnTriGiaHDChanging(System.Nullable<int> value);
    partial void OnTriGiaHDChanged();
    partial void OnNgayGiaoDKChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoDKChanged();
    partial void OnNgayNgThuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNgThuChanged();
    #endregion
		
		public HOPDONG()
		{
			this._CHITIET_HDs = new EntitySet<CHITIET_HD>(new Action<CHITIET_HD>(this.attach_CHITIET_HDs), new Action<CHITIET_HD>(this.detach_CHITIET_HDs));
			this._PHIEUTHUs = new EntitySet<PHIEUTHU>(new Action<PHIEUTHU>(this.attach_PHIEUTHUs), new Action<PHIEUTHU>(this.detach_PHIEUTHUs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SoHD
		{
			get
			{
				return this._SoHD;
			}
			set
			{
				if ((this._SoHD != value))
				{
					this.OnSoHDChanging(value);
					this.SendPropertyChanging();
					this._SoHD = value;
					this.SendPropertyChanged("SoHD");
					this.OnSoHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHD", DbType="Date")]
		public System.Nullable<System.DateTime> NgayHD
		{
			get
			{
				return this._NgayHD;
			}
			set
			{
				if ((this._NgayHD != value))
				{
					this.OnNgayHDChanging(value);
					this.SendPropertyChanging();
					this._NgayHD = value;
					this.SendPropertyChanged("NgayHD");
					this.OnNgayHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoXe", DbType="Char(10)")]
		public string SoXe
		{
			get
			{
				return this._SoXe;
			}
			set
			{
				if ((this._SoXe != value))
				{
					this.OnSoXeChanging(value);
					this.SendPropertyChanging();
					this._SoXe = value;
					this.SendPropertyChanged("SoXe");
					this.OnSoXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TriGiaHD", DbType="Int")]
		public System.Nullable<int> TriGiaHD
		{
			get
			{
				return this._TriGiaHD;
			}
			set
			{
				if ((this._TriGiaHD != value))
				{
					this.OnTriGiaHDChanging(value);
					this.SendPropertyChanging();
					this._TriGiaHD = value;
					this.SendPropertyChanged("TriGiaHD");
					this.OnTriGiaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaoDK", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGiaoDK
		{
			get
			{
				return this._NgayGiaoDK;
			}
			set
			{
				if ((this._NgayGiaoDK != value))
				{
					this.OnNgayGiaoDKChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaoDK = value;
					this.SendPropertyChanged("NgayGiaoDK");
					this.OnNgayGiaoDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNgThu", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNgThu
		{
			get
			{
				return this._NgayNgThu;
			}
			set
			{
				if ((this._NgayNgThu != value))
				{
					this.OnNgayNgThuChanging(value);
					this.SendPropertyChanging();
					this._NgayNgThu = value;
					this.SendPropertyChanged("NgayNgThu");
					this.OnNgayNgThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_CHITIET_HD", Storage="_CHITIET_HDs", ThisKey="SoHD", OtherKey="SoHD")]
		public EntitySet<CHITIET_HD> CHITIET_HDs
		{
			get
			{
				return this._CHITIET_HDs;
			}
			set
			{
				this._CHITIET_HDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_PHIEUTHU", Storage="_PHIEUTHUs", ThisKey="SoHD", OtherKey="SoHD")]
		public EntitySet<PHIEUTHU> PHIEUTHUs
		{
			get
			{
				return this._PHIEUTHUs;
			}
			set
			{
				this._PHIEUTHUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOPDONG", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HOPDONGs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HOPDONGs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIET_HDs(CHITIET_HD entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = this;
		}
		
		private void detach_CHITIET_HDs(CHITIET_HD entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = null;
		}
		
		private void attach_PHIEUTHUs(PHIEUTHU entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = this;
		}
		
		private void detach_PHIEUTHUs(PHIEUTHU entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _TenKH;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private EntitySet<HOPDONG> _HOPDONGs;
		
		private EntitySet<PHIEUTHU> _PHIEUTHUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._HOPDONGs = new EntitySet<HOPDONG>(new Action<HOPDONG>(this.attach_HOPDONGs), new Action<HOPDONG>(this.detach_HOPDONGs));
			this._PHIEUTHUs = new EntitySet<PHIEUTHU>(new Action<PHIEUTHU>(this.attach_PHIEUTHUs), new Action<PHIEUTHU>(this.detach_PHIEUTHUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="Char(15)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOPDONG", Storage="_HOPDONGs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<HOPDONG> HOPDONGs
		{
			get
			{
				return this._HOPDONGs;
			}
			set
			{
				this._HOPDONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUTHU", Storage="_PHIEUTHUs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<PHIEUTHU> PHIEUTHUs
		{
			get
			{
				return this._PHIEUTHUs;
			}
			set
			{
				this._PHIEUTHUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_PHIEUTHUs(PHIEUTHU entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_PHIEUTHUs(PHIEUTHU entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG")]
	public partial class NGUOIDUNG1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenNguoiDung;
		
		private string _MatKhau;
		
		private System.Nullable<int> _MaKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenNguoiDungChanging(string value);
    partial void OnTenNguoiDungChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    #endregion
		
		public NGUOIDUNG1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiDung", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenNguoiDung
		{
			get
			{
				return this._TenNguoiDung;
			}
			set
			{
				if ((this._TenNguoiDung != value))
				{
					this.OnTenNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiDung = value;
					this.SendPropertyChanged("TenNguoiDung");
					this.OnTenNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(20)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTHU")]
	public partial class PHIEUTHU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoPT;
		
		private System.Nullable<System.DateTime> _NgayLapPT;
		
		private int _SoHD;
		
		private int _MaKH;
		
		private string _HoTen;
		
		private System.Nullable<int> _SoTienThu;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<HOPDONG> _HOPDONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoPTChanging(string value);
    partial void OnSoPTChanged();
    partial void OnNgayLapPTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapPTChanged();
    partial void OnSoHDChanging(int value);
    partial void OnSoHDChanged();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnSoTienThuChanging(System.Nullable<int> value);
    partial void OnSoTienThuChanged();
    #endregion
		
		public PHIEUTHU()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._HOPDONG = default(EntityRef<HOPDONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPT", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoPT
		{
			get
			{
				return this._SoPT;
			}
			set
			{
				if ((this._SoPT != value))
				{
					this.OnSoPTChanging(value);
					this.SendPropertyChanging();
					this._SoPT = value;
					this.SendPropertyChanged("SoPT");
					this.OnSoPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapPT", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLapPT
		{
			get
			{
				return this._NgayLapPT;
			}
			set
			{
				if ((this._NgayLapPT != value))
				{
					this.OnNgayLapPTChanging(value);
					this.SendPropertyChanging();
					this._NgayLapPT = value;
					this.SendPropertyChanged("NgayLapPT");
					this.OnNgayLapPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SoHD
		{
			get
			{
				return this._SoHD;
			}
			set
			{
				if ((this._SoHD != value))
				{
					if (this._HOPDONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoHDChanging(value);
					this.SendPropertyChanging();
					this._SoHD = value;
					this.SendPropertyChanged("SoHD");
					this.OnSoHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienThu", DbType="Int")]
		public System.Nullable<int> SoTienThu
		{
			get
			{
				return this._SoTienThu;
			}
			set
			{
				if ((this._SoTienThu != value))
				{
					this.OnSoTienThuChanging(value);
					this.SendPropertyChanging();
					this._SoTienThu = value;
					this.SendPropertyChanged("SoTienThu");
					this.OnSoTienThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUTHU", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.PHIEUTHUs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHUs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_PHIEUTHU", Storage="_HOPDONG", ThisKey="SoHD", OtherKey="SoHD", IsForeignKey=true)]
		public HOPDONG HOPDONG
		{
			get
			{
				return this._HOPDONG.Entity;
			}
			set
			{
				HOPDONG previousValue = this._HOPDONG.Entity;
				if (((previousValue != value) 
							|| (this._HOPDONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOPDONG.Entity = null;
						previousValue.PHIEUTHUs.Remove(this);
					}
					this._HOPDONG.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHUs.Add(this);
						this._SoHD = value.SoHD;
					}
					else
					{
						this._SoHD = default(int);
					}
					this.SendPropertyChanged("HOPDONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THO")]
	public partial class THO1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTho;
		
		private string _TenTho;
		
		private System.Nullable<int> _Nhom;
		
		private System.Nullable<int> _NhomTruong;
		
		private EntitySet<THO1> _THO1s;
		
		private EntityRef<THO1> _THO11;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThoChanging(int value);
    partial void OnMaThoChanged();
    partial void OnTenThoChanging(string value);
    partial void OnTenThoChanged();
    partial void OnNhomChanging(System.Nullable<int> value);
    partial void OnNhomChanged();
    partial void OnNhomTruongChanging(System.Nullable<int> value);
    partial void OnNhomTruongChanged();
    #endregion
		
		public THO1()
		{
			this._THO1s = new EntitySet<THO1>(new Action<THO1>(this.attach_THO1s), new Action<THO1>(this.detach_THO1s));
			this._THO11 = default(EntityRef<THO1>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTho", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTho
		{
			get
			{
				return this._MaTho;
			}
			set
			{
				if ((this._MaTho != value))
				{
					this.OnMaThoChanging(value);
					this.SendPropertyChanging();
					this._MaTho = value;
					this.SendPropertyChanged("MaTho");
					this.OnMaThoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTho", DbType="NVarChar(50)")]
		public string TenTho
		{
			get
			{
				return this._TenTho;
			}
			set
			{
				if ((this._TenTho != value))
				{
					this.OnTenThoChanging(value);
					this.SendPropertyChanging();
					this._TenTho = value;
					this.SendPropertyChanged("TenTho");
					this.OnTenThoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhom", DbType="Int")]
		public System.Nullable<int> Nhom
		{
			get
			{
				return this._Nhom;
			}
			set
			{
				if ((this._Nhom != value))
				{
					this.OnNhomChanging(value);
					this.SendPropertyChanging();
					this._Nhom = value;
					this.SendPropertyChanged("Nhom");
					this.OnNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomTruong", DbType="Int")]
		public System.Nullable<int> NhomTruong
		{
			get
			{
				return this._NhomTruong;
			}
			set
			{
				if ((this._NhomTruong != value))
				{
					if (this._THO11.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNhomTruongChanging(value);
					this.SendPropertyChanging();
					this._NhomTruong = value;
					this.SendPropertyChanged("NhomTruong");
					this.OnNhomTruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THO1_THO1", Storage="_THO1s", ThisKey="MaTho", OtherKey="NhomTruong")]
		public EntitySet<THO1> THO1s
		{
			get
			{
				return this._THO1s;
			}
			set
			{
				this._THO1s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THO1_THO1", Storage="_THO11", ThisKey="NhomTruong", OtherKey="MaTho", IsForeignKey=true)]
		public THO1 THO11
		{
			get
			{
				return this._THO11.Entity;
			}
			set
			{
				THO1 previousValue = this._THO11.Entity;
				if (((previousValue != value) 
							|| (this._THO11.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THO11.Entity = null;
						previousValue.THO1s.Remove(this);
					}
					this._THO11.Entity = value;
					if ((value != null))
					{
						value.THO1s.Add(this);
						this._NhomTruong = value.MaTho;
					}
					else
					{
						this._NhomTruong = default(Nullable<int>);
					}
					this.SendPropertyChanged("THO11");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THO1s(THO1 entity)
		{
			this.SendPropertyChanging();
			entity.THO11 = this;
		}
		
		private void detach_THO1s(THO1 entity)
		{
			this.SendPropertyChanging();
			entity.THO11 = null;
		}
	}
}
#pragma warning restore 1591
